/* 
 * PacerPro
 *
 * PacerPro API documentation.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: ken@pacerpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.PacerPro.Client;
using IO.PacerPro.Model;

namespace IO.PacerPro.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthenticationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Initial authentication.
        /// </summary>
        /// <remarks>
        /// Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Session</returns>
        Session SessionCreate (User user);

        /// <summary>
        /// Initial authentication.
        /// </summary>
        /// <remarks>
        /// Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>ApiResponse of Session</returns>
        ApiResponse<Session> SessionCreateWithHttpInfo (User user);
        /// <summary>
        /// Revoke all JWT tokens (logout).
        /// </summary>
        /// <remarks>
        /// Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Empty</returns>
        Empty SessionDelete (string authorization = null);

        /// <summary>
        /// Revoke all JWT tokens (logout).
        /// </summary>
        /// <remarks>
        /// Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> SessionDeleteWithHttpInfo (string authorization = null);
        /// <summary>
        /// Refresh authentication token
        /// </summary>
        /// <remarks>
        /// Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Session</returns>
        Session SessionRefresh (string authorization = null);

        /// <summary>
        /// Refresh authentication token
        /// </summary>
        /// <remarks>
        /// Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Session</returns>
        ApiResponse<Session> SessionRefreshWithHttpInfo (string authorization = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Initial authentication.
        /// </summary>
        /// <remarks>
        /// Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Task of Session</returns>
        System.Threading.Tasks.Task<Session> SessionCreateAsync (User user);

        /// <summary>
        /// Initial authentication.
        /// </summary>
        /// <remarks>
        /// Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        System.Threading.Tasks.Task<ApiResponse<Session>> SessionCreateAsyncWithHttpInfo (User user);
        /// <summary>
        /// Revoke all JWT tokens (logout).
        /// </summary>
        /// <remarks>
        /// Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> SessionDeleteAsync (string authorization = null);

        /// <summary>
        /// Revoke all JWT tokens (logout).
        /// </summary>
        /// <remarks>
        /// Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> SessionDeleteAsyncWithHttpInfo (string authorization = null);
        /// <summary>
        /// Refresh authentication token
        /// </summary>
        /// <remarks>
        /// Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Session</returns>
        System.Threading.Tasks.Task<Session> SessionRefreshAsync (string authorization = null);

        /// <summary>
        /// Refresh authentication token
        /// </summary>
        /// <remarks>
        /// Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        System.Threading.Tasks.Task<ApiResponse<Session>> SessionRefreshAsyncWithHttpInfo (string authorization = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthenticationApi : IAuthenticationApi
    {
        private IO.PacerPro.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthenticationApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.PacerPro.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthenticationApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.PacerPro.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.PacerPro.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Initial authentication. Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Session</returns>
        public Session SessionCreate (User user)
        {
             ApiResponse<Session> localVarResponse = SessionCreateWithHttpInfo(user);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Initial authentication. Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>ApiResponse of Session</returns>
        public ApiResponse< Session > SessionCreateWithHttpInfo (User user)
        {
            // verify the required parameter 'user' is set
            if (user == null)
                throw new ApiException(400, "Missing required parameter 'user' when calling AuthenticationApi->SessionCreate");

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (user != null && user.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(user); // http body (model) parameter
            }
            else
            {
                localVarPostBody = user; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Session>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Session) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Session)));
            
        }

        /// <summary>
        /// Initial authentication. Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Task of Session</returns>
        public async System.Threading.Tasks.Task<Session> SessionCreateAsync (User user)
        {
             ApiResponse<Session> localVarResponse = await SessionCreateAsyncWithHttpInfo(user);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Initial authentication. Use this call to generate an authorization token for use in future calls. Provide your PacerPro credentials (email &amp; password) in the User object. You will get a Session object in return.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="user">User credentials</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Session>> SessionCreateAsyncWithHttpInfo (User user)
        {
            // verify the required parameter 'user' is set
            if (user == null)
                throw new ApiException(400, "Missing required parameter 'user' when calling AuthenticationApi->SessionCreate");

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (user != null && user.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(user); // http body (model) parameter
            }
            else
            {
                localVarPostBody = user; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Session>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Session) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Session)));
            
        }

        /// <summary>
        /// Revoke all JWT tokens (logout). Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Empty</returns>
        public Empty SessionDelete (string authorization = null)
        {
             ApiResponse<Empty> localVarResponse = SessionDeleteWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke all JWT tokens (logout). Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > SessionDeleteWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Empty) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
            
        }

        /// <summary>
        /// Revoke all JWT tokens (logout). Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> SessionDeleteAsync (string authorization = null)
        {
             ApiResponse<Empty> localVarResponse = await SessionDeleteAsyncWithHttpInfo(authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Revoke all JWT tokens (logout). Revoke JWT tokens by spinning a new JTI. All current tokens will no longer work.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> SessionDeleteAsyncWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Empty) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
            
        }

        /// <summary>
        /// Refresh authentication token Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Session</returns>
        public Session SessionRefresh (string authorization = null)
        {
             ApiResponse<Session> localVarResponse = SessionRefreshWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Refresh authentication token Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Session</returns>
        public ApiResponse< Session > SessionRefreshWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionRefresh", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Session>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Session) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Session)));
            
        }

        /// <summary>
        /// Refresh authentication token Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Session</returns>
        public async System.Threading.Tasks.Task<Session> SessionRefreshAsync (string authorization = null)
        {
             ApiResponse<Session> localVarResponse = await SessionRefreshAsyncWithHttpInfo(authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Refresh authentication token Using a valid auth token, you can use this to refresh it, thus extending the time unti it expires. See POST /session for instructions on the initial authentication.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Session>> SessionRefreshAsyncWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SessionRefresh", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Session>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Session) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Session)));
            
        }

    }
}
