/* 
 * PacerPro
 *
 * PacerPro API documentation.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: ken@pacerpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.PacerPro.Client;
using IO.PacerPro.Model;

namespace IO.PacerPro.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMattersApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// A collection of matters.
        /// </summary>
        /// <remarks>
        /// Get all matters relevant to the firm.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>List&lt;Matter&gt;</returns>
        List<Matter> MattersGetCollection (string authorization = null);

        /// <summary>
        /// A collection of matters.
        /// </summary>
        /// <remarks>
        /// Get all matters relevant to the firm.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of List&lt;Matter&gt;</returns>
        ApiResponse<List<Matter>> MattersGetCollectionWithHttpInfo (string authorization = null);
        /// <summary>
        /// A single matter.
        /// </summary>
        /// <remarks>
        /// Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Matter</returns>
        Matter MattersGetOne (string matterId, string authorization = null);

        /// <summary>
        /// A single matter.
        /// </summary>
        /// <remarks>
        /// Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Matter</returns>
        ApiResponse<Matter> MattersGetOneWithHttpInfo (string matterId, string authorization = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// A collection of matters.
        /// </summary>
        /// <remarks>
        /// Get all matters relevant to the firm.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of List&lt;Matter&gt;</returns>
        System.Threading.Tasks.Task<List<Matter>> MattersGetCollectionAsync (string authorization = null);

        /// <summary>
        /// A collection of matters.
        /// </summary>
        /// <remarks>
        /// Get all matters relevant to the firm.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Matter&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Matter>>> MattersGetCollectionAsyncWithHttpInfo (string authorization = null);
        /// <summary>
        /// A single matter.
        /// </summary>
        /// <remarks>
        /// Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Matter</returns>
        System.Threading.Tasks.Task<Matter> MattersGetOneAsync (string matterId, string authorization = null);

        /// <summary>
        /// A single matter.
        /// </summary>
        /// <remarks>
        /// Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </remarks>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Matter)</returns>
        System.Threading.Tasks.Task<ApiResponse<Matter>> MattersGetOneAsyncWithHttpInfo (string matterId, string authorization = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MattersApi : IMattersApi
    {
        private IO.PacerPro.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MattersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MattersApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.PacerPro.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MattersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MattersApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.PacerPro.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.PacerPro.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// A collection of matters. Get all matters relevant to the firm.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>List&lt;Matter&gt;</returns>
        public List<Matter> MattersGetCollection (string authorization = null)
        {
             ApiResponse<List<Matter>> localVarResponse = MattersGetCollectionWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// A collection of matters. Get all matters relevant to the firm.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of List&lt;Matter&gt;</returns>
        public ApiResponse< List<Matter> > MattersGetCollectionWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/matters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MattersGetCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Matter>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Matter>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Matter>)));
            
        }

        /// <summary>
        /// A collection of matters. Get all matters relevant to the firm.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of List&lt;Matter&gt;</returns>
        public async System.Threading.Tasks.Task<List<Matter>> MattersGetCollectionAsync (string authorization = null)
        {
             ApiResponse<List<Matter>> localVarResponse = await MattersGetCollectionAsyncWithHttpInfo(authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// A collection of matters. Get all matters relevant to the firm.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Matter&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Matter>>> MattersGetCollectionAsyncWithHttpInfo (string authorization = null)
        {

            var localVarPath = "/matters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MattersGetCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Matter>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Matter>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Matter>)));
            
        }

        /// <summary>
        /// A single matter. Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Matter</returns>
        public Matter MattersGetOne (string matterId, string authorization = null)
        {
             ApiResponse<Matter> localVarResponse = MattersGetOneWithHttpInfo(matterId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// A single matter. Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>ApiResponse of Matter</returns>
        public ApiResponse< Matter > MattersGetOneWithHttpInfo (string matterId, string authorization = null)
        {
            // verify the required parameter 'matterId' is set
            if (matterId == null)
                throw new ApiException(400, "Missing required parameter 'matterId' when calling MattersApi->MattersGetOne");

            var localVarPath = "/matters/{matterId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (matterId != null) localVarPathParams.Add("matterId", Configuration.ApiClient.ParameterToString(matterId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MattersGetOne", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Matter>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Matter) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Matter)));
            
        }

        /// <summary>
        /// A single matter. Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of Matter</returns>
        public async System.Threading.Tasks.Task<Matter> MattersGetOneAsync (string matterId, string authorization = null)
        {
             ApiResponse<Matter> localVarResponse = await MattersGetOneAsyncWithHttpInfo(matterId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// A single matter. Get a single matter, specified by &#x60;matterId&#x60; in the path.
        /// </summary>
        /// <exception cref="IO.PacerPro.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matterId">The database identifier of the matter.</param>
        /// <param name="authorization">Bearer {...JSON Web Token...} (optional)</param>
        /// <returns>Task of ApiResponse (Matter)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Matter>> MattersGetOneAsyncWithHttpInfo (string matterId, string authorization = null)
        {
            // verify the required parameter 'matterId' is set
            if (matterId == null)
                throw new ApiException(400, "Missing required parameter 'matterId' when calling MattersApi->MattersGetOne");

            var localVarPath = "/matters/{matterId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (matterId != null) localVarPathParams.Add("matterId", Configuration.ApiClient.ParameterToString(matterId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MattersGetOne", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Matter>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Matter) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Matter)));
            
        }

    }
}
