/* 
 * PacerPro
 *
 * PacerPro API documentation.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: ken@pacerpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.PacerPro.Client;
using IO.PacerPro.Api;
using IO.PacerPro.Model;

namespace IO.PacerPro.Test
{
    /// <summary>
    ///  Class for testing MattersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MattersApiTests
    {
        private MattersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MattersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MattersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MattersApi
            //Assert.IsInstanceOfType(typeof(MattersApi), instance, "instance is a MattersApi");
        }

        
        /// <summary>
        /// Test MattersGetCollection
        /// </summary>
        [Test]
        public void MattersGetCollectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //var response = instance.MattersGetCollection(authorization);
            //Assert.IsInstanceOf<List<Matter>> (response, "response is List<Matter>");
        }
        
        /// <summary>
        /// Test MattersGetOne
        /// </summary>
        [Test]
        public void MattersGetOneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string matterId = null;
            //string authorization = null;
            //var response = instance.MattersGetOne(matterId, authorization);
            //Assert.IsInstanceOf<Matter> (response, "response is Matter");
        }
        
    }

}
